### ISSUE TITLE
how kernel to internal emmc?

### ISSUE THREAD

**Issue by ulno** [caninos-loucos/labrador-linux#4]
The new features that we can test out n the current sd-card image are pretty nice. I also have not much trouble getting the data of the image on the internal emmc.

However, how do I replace the kernel of the internal memory? Where is it saved? What is the command to flash the new kernel from the sd-card.

It also would be nice, if that one could be distributed alone and not in such a huge image.

**Comment by ThalysonZatt** [comment]
There are two ways to update the kernel:

1) Using an SD Card to flash the image
Download the image and write it into an SD Card. With the SD Card inside the Labrador, hold the recovery button while powering on the board. Once the board is on, wait a couple of seconds while pressing it and then you can release it and it will start flashing. You can also check on the status and log of the flashing process through the serial interface in the baseboard, with a USB-TTL converter at 115200 baud rate.

--------------------------------------------------------------------

2) Changing just the kernel files

Download the files and unzip it. Once the files are in the Labrador, use those commands to update:

sudo mkdir /media/caninos/BOOT
sudo mount /dev/mmcblk2p1 /media/caninos/BOOT
sudo cp -r /src/kernel.dtb /media/caninos/BOOT
sudo cp -r /src/uImage /media/caninos/BOOT
sudo cp -r /src/lib/modules /lib/
sudo su
echo "blacklist labrador_s500_thermal" >> /etc/modprobe.d/blacklist.conf"
sudo sync
sudo umount /media/caninos/BOOT
sudo rm -r /media/caninos/BOOT/
sudo reboot

Attention: You need to change “src” by the path the new kernel is.
The command "echo "blacklist labrador_s500_thermal" >> /etc/modprobe.d/blacklist.conf"" is only needed in the v0.9 version of kernel 4.

--------------------------------------------------------------------

The kernel files and the images are found here: http://downloads.caninosloucos.org.br/

![adfu_button](https://user-images.githubusercontent.com/12140106/64791591-50b95780-d54e-11e9-8876-6bd21407d02b.png)
